Repository Git21221/form-snippet, pull requests merged in 2024-10, with the labels that each got.

#10 Add Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest

#7 overriding input default classes with custom tailwind classes
  package.json
  src/components/Input/Input.tsx
  test/src/App.jsx
  test/tailwind.config.js
Labels: hacktoberfest-accepted, level 1, hacktoberfest

#15 Implement Auto Labeler GitHub Action for Issues and Pull Requests
  .github/workflows/greetings.yml
  .github/workflows/labeler.yml
  CONTRIBUTING.md
  README.md
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#27 ADD Modalformsubmission which will open on form submission
  src/components/FormModal/FormModal.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#26 ADD: Datepicker component
  .github/workflows/labeler.yml
  package.json
  src/components/DatePicker/DatePicker.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#29 ADD: Checkbox component
  src/components/Checkbox/Checkbox.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#33 Implemented Skeleton Loader
  src/components/Skeleton/Skeleton.css
  src/components/Skeleton/Skeleton.tsx
  src/index.ts
  test/src/App.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level 2, hacktoberfest

#41 ADD CONTACT SECTION
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level 1, hacktoberfest
